on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            python-include: "python3.10"
            tox-env: "py310"
          - python-version: "pypy3.10"
            python-include: "pypy3.10"
            tox-env: "pypy310"
    steps:
      - run: sudo apt-get install -qq liblzo2-dev
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - run: git lfs pull
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "setup.py"
      - run: pip install tox
      - run: sed -i 's/\[tool.setuptools_scm\]/\[tool.setuptools_scm\]\nlocal_scheme = "no-local-version"/' pyproject.toml
      - env:
          C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/${{ matrix.python-include }}
        run: tox -e ${{ matrix.tox-env }}
